AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  CloudFormation template to create EC2 instance with security group

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-08eb150f611ca277f
      InstanceType: t3.micro
      SecurityGroups:
        - sg-00917ed2150208fe7
      KeyName: CF-Keys
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          #!/bin/bash
          sudo apt -y update 
          sudo apt -y upgrade 
          cd /root/
          sudo git clone https://github.com/Iqrazamir1/WordPressPractise.git
          sudo chmod -R 755 /root/WordPressPractise
          sudo bash /root/WordPressPractise/lemp_stack_automate.sh

  # our EC2 security group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22

  # our second EC2 security group
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable accessing server via port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
