AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  # CloudFormation template to create EC2 instance with security group

Resources:
  # Defines the EC2 instance resource
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-08eb150f611ca277f
      InstanceType: t3.micro
      SecurityGroups:
        - !Ref SSHSecurityGroup  # Reference to a predefined security group (to be defined elsewhere)
        - !Ref ServerSecurityGroup  # Reference to a second security group
      # SSH key pair used to connect to the instance securely
      KeyName: Wordpress
      # UserData script that runs automatically when the instance starts, Base64 encoded
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt -y update 
          sudo apt -y upgrade 
          cd /root/
          sudo git clone https://github.com/Iqrazamir1/WordPressPractise.git
          sudo chmod -R 755 /root/WordPressPractise
          sudo bash /root/WordPressPractise/lemp_stack_automate.sh

  # Elastic IP resource, provides a static public IP address to the instance
  MyElasticIP:
    Type: AWS::EC2::EIP

  # Associates the Elastic IP with the EC2 instance
  MyEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      # Associate the EIP with the EC2 instance
      InstanceId: !Ref MyInstance
      # Reference the Elastic IP to associate with the instance
      EIP: !Ref MyElasticIP

  # Defines the security group that controls network access to the EC2 instance
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      # Description of the security group
      GroupDescription: Enable access via ports 22, 80, and 443
      # Ingress rules to allow inbound traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22  # Allows SSH access on port 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Open to all IP addresses (not recommended for production)
        - IpProtocol: tcp
          FromPort: 80  # Allows HTTP traffic on port 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  # Open to all IP addresses
        - IpProtocol: tcp
          FromPort: 443  # Allows HTTPS traffic on port 443
          ToPort: 443
          CidrIp: 0.0.0.0/0  # Open to all IP addresses
